DROP TABLE IF EXISTS MyEvents;



CREATE TABLE MyEvents (
	id VARCHAR PRIMARY KEY NOT NULL ,
  	event VARCHAR NOT NULL,
  	eventdate VARCHAR NOT NULL,
  	eventtime VARCHAR,
  	address VARCHAR NOT NULL,
  	category VARCHAR NOT NULL,
  	image VARCHAR NOT NULL
);
