DROP TABLE IF EXISTS MyEvents;



CREATE TABLE MyEvents (
	id SERIAL PRIMARY KEY NOT NULL ,
  	event VARCHAR NOT NULL,
  	date VARCHAR NOT NULL,
  	time VARCHAR,
  	address VARCHAR NOT NULL,
  	category VARCHAR NOT NULL,
  	image VARCHAR NOT NULL
);
